### ISSUE TITLE
Unable to sign in with Google with g suite account

### ISSUE THREAD

**Issue by kunwar231** [imjog/Social-Logins-iOS#13]
Using any g suit account doesn't allows to login into the app. Error says "your admin requires you to set a passcode on this device to access the accounts." . Whereas no such thing happens when using Google sign in with zoom app me or any other app for that matter.

**Comment by jogendra** [comment]
Hey, @kunwar231 This project is 3+ years old and I am sure a lot changed in Google Sign-In APIs/SDKs. Please refer to their latest documentations.

Also, feel free to open a PR with latest changes.

**Comment by kunwar231** [comment]
Hi,
Then please delete the repo or make it private as it is of no use now and
you are clearly not ready to update it

**Comment by jogendra** [comment]
@kunwar231 would be better if you mind your own shit.
